networks:
  my_net_lr_3:

volumes:
  db_volume:

services:


  db:
    build:
      context: DB
    container_name:
      db_postgres_lr_3
    ports:
     - "54322:5432" # DElete ThiS
    volumes:
      - db_volume:/home/
    networks:
      - my_net_lr_3
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # api:
  #   build:
  #     context: api_server  
  #   container_name: api_lr_3
  #   ports:
  #     - "15000:15000"
  #   networks:
  #     - my_net_lr_3
  #   restart: always
  #   depends_on:
  #     - db

  
#   bot:
#     build:
#       context: Bot  
#     container_name: bot_lr_3
# #    ports:
# #      - "15001:15001"
#     networks:
#       - my_net_lr_3
#     restart: always
#     depends_on:
#       - api
  
  
  # pgadmin:
  #   build:
  #     context: pgAdmin  
  #   container_name: pgadmin_lr_3
  #   ports:
  #     - "8888:80"
  #   networks:
  #     - my_net_lr_3
  #   restart: always
  #   depends_on:
  #     - db

