networks:
  my_net_lr_3:

volumes:
  db_volume:

services:


  db:
    build:
      context: DB
    container_name:
      db_postgres_lr_3
    volumes:
      - db_volume:/home/
    networks:
      - my_net_lr_3
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  api_server:
    build:
      context: api_server
      args:
        UID: ${UID}
        GID: ${GID}
    restart: always
    ports:
      - "15000:15000"
    environment:
      TZ: ${TZ}
    env_file:
      - .env
    container_name:
      api_server_lr_3
    networks:
      - my_net_lr_3
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


  pgadmin:
    build:
      context: pgAdmin  
    container_name: pgadmin_lr_3
    ports:
      - "5432:5432"  # пробрасываем порт 5432 на хост
    networks:
      - my_net_lr_3
    restart: always
    depends_on:
      - db

