      
# Название нашего workflow - будет отображаться в GitHub Actions
name: Basic CI Checks

#Триггеры
on:
  push: # При каждом push (отправке кода)
    branches: [ main ]
  pull_request: # При каждом pull request (запросе на слияние)
    branches: [ main ]

#Задачи, которые будут выполняться
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Забрать (скачать) код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4 # Используем готовое действие (action) от GitHub

      # --- Сборка Фронтенда ---
      - name: Setup Node.js # Название шага
        uses: actions/setup-node@v4 # Используем готовое действие для настройки Node.js
        with:
          node-version: '20' # Укажите версию Node.js, которую вы используете (например, 18, 20)

      - name: Install Frontend Dependencies #Установка зависимостей фронтенда
        working-directory: ./Front/front
        run: npm install

      - name: Build Frontend #Сборка фронтенда
        working-directory: ./Front/front
        run: npm run build

      # --- Проверки для Бэкенда ---
      - name: Setup Python #Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Backend Dependencies #Установка зависимостей API
        working-directory: ./api_server
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build API Docker Image
        working-directory: ./api_server # Где лежит Dockerfile для API
        run: docker build -t myusername/my-api-image:latest .

      - name: Build Bot Docker Image
        working-directory: ./Bot # Где лежит Dockerfile для Бота
        run: docker build -t myusername/my-bot-image:latest .

      # --- Вход в GitHub Container Registry ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Имя пользователя, инициировавшего workflow
          password: ${{ secrets.GITHUB_TOKEN }} # Стандартный токен, предоставляемый GitHub Actions

      # --- Сборка и Push Docker-образа API ---
      - name: Extract metadata (tags, labels) for API Docker image
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/my-api-image
          tags: |
            type=sha,prefix=,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api_server # Путь к Dockerfile и контексту сборки для API
          push: ${{ github.event_name != 'pull_request' }} # Пушим только если это не pull request (т.е. push в main)
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      # --- Сборка и Push Docker-образа Бота ---
      - name: Extract metadata (tags, labels) for Bot Docker image
        id: meta_bot
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/my-bot-image # Имя образа (замените my-bot-image)
          tags: |
            type=sha,prefix=,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Bot Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Bot # Путь к Dockerfile и контексту сборки для Бота
          push: ${{ github.event_name != 'pull_request' }} # Пушим только если это не pull request
          tags: ${{ steps.meta_bot.outputs.tags }}
          labels: ${{ steps.meta_bot.outputs.labels }}
    
      # --- Развертывание на сервере ---
      - name: Deploy to Server
        # Этот шаг будет выполняться только при push в main, а не для PR
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3 # Популярное действие для SSH
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 5252 # Порт SSH, по умолчанию 22, можно изменить если у вас другой
          script: | # Команды, которые будут выполнены на сервере
            echo "Starting deployment..."
            cd ${{ secrets.PROJECT_PATH_ON_SERVER }}
            echo "Pulling latest images..."
            docker-compose pull api bot # Укажите имена ваших сервисов из docker-compose.yml
            echo "Restarting services..."
            # Важно: используйте docker compose (с пробелом), если у вас Docker Compose V2.
            # Если Docker Compose V1, то docker-compose (с дефисом).
            docker-compose up -d --force-recreate --remove-orphans api bot nginx # Перезапускаем нужные сервисы
            echo "Cleaning up old Docker images..."
            docker image prune -af # Удаляем все неиспользуемые образы (с флагом -a для всех неиспользуемых, не только "dangling")
            echo "Deployment finished!"
